export const categories = [
    { id: 1, title: 'Educação' },
    { id: 2, title: 'Alimentação' },
    { id: 3, title: 'Lazer' },
    { id: 4, title: 'Hobbies' },
    { id: 5, title: 'Assinaturas' },
    { id: 6, title: 'Casa' },
    { id: 7, title: 'Compras' },
    { id: 8, title: 'Saúde' },
    { id: 9, title: 'Cuidados pessoais' },
    { id: 10, title: 'Dívidas' },
    { id: 11, title: 'Família' },
    { id: 12, title: 'Impostos' },
    { id: 13, title: 'Transporte' },
    { id: 14, title: 'Viagens' },
    { id: 15, title: 'Doações' },
    { id: 16, title: 'Investimentos' },
    { id: 17, title: 'Emergências' },
    { id: 18, title: 'Animais de estimação' },
    { id: 19, title: 'Roupas' },
    { id: 20, title: 'Telefonia e Internet' },
    { id: 21, title: 'Presentes' },
    { id: 22, title: 'Tecnologia' },
    { id: 23, title: 'Entretenimento' },
    { id: 24, title: 'Beleza e cosméticos' },
    { id: 25, title: 'Carro' },
    { id: 26, title: 'Seguros' },
    { id: 27, title: 'Saúde mental' },
    { id: 28, title: 'Imóveis' },
    { id: 29, title: 'Cuidado infantil' },
    { id: 30, title: 'Aposentadoria' },
    { id: 31, title: 'Salário' },
    { id: 32, title: 'Bônus' },
    { id: 33, title: 'Renda extra' },
    { id: 34, title: 'Investimentos retorno' },
    { id: 35, title: 'Poupança' }
];

export enum Categories {
    'Educação' = 1,
    'Alimentação',
    'Lazer',
    'Hobbies',
    'Assinaturas',
    'Casa',
    'Compras',
    'Saúde',
    'Cuidados pessoais',
    'Dívidas',
    'Família',
    'Impostos',
    'Transporte',
    'Viagens',
    'Doações',
    'Investimentos',
    'Emergências',
    'Animais de estimação',
    'Roupas',
    'Telefonia e Internet',
    'Presentes',
    'Tecnologia',
    'Entretenimento',
    'Beleza e cosméticos',
    'Carro',
    'Seguros',
    'Saúde mental',
    'Imóveis',
    'Cuidado infantil',
    'Aposentadoria',
    'Salário',
    'Bônus',
    'Renda extra',
    'Investimentos retorno',
    'Poupança'
}
