export const categories = [
    { id: 1, name: 'Educação' },
    { id: 2, name: 'Alimentação' },
    { id: 3, name: 'Lazer' },
    { id: 4, name: 'Hobbies' },
    { id: 5, name: 'Assinaturas' },
    { id: 6, name: 'Casa' },
    { id: 7, name: 'Compras' },
    { id: 8, name: 'Saúde' },
    { id: 9, name: 'Cuidados pessoais' },
    { id: 10, name: 'Dívidas' },
    { id: 11, name: 'Família' },
    { id: 12, name: 'Impostos' },
    { id: 13, name: 'Transporte' },
    { id: 14, name: 'Viagens' },
    { id: 15, name: 'Doações' },
    { id: 16, name: 'Investimentos' },
    { id: 17, name: 'Emergências' },
    { id: 18, name: 'Animais de estimação' },
    { id: 19, name: 'Roupas' },
    { id: 20, name: 'Telefonia e Internet' },
    { id: 21, name: 'Presentes' },
    { id: 22, name: 'Tecnologia' },
    { id: 23, name: 'Entretenimento' },
    { id: 24, name: 'Beleza e cosméticos' },
    { id: 25, name: 'Carro' },
    { id: 26, name: 'Seguros' },
    { id: 27, name: 'Saúde mental' },
    { id: 28, name: 'Imóveis' },
    { id: 29, name: 'Cuidado infantil' },
    { id: 30, name: 'Aposentadoria' },
    { id: 31, name: 'Salário' },
    { id: 32, name: 'Bônus' },
    { id: 33, name: 'Renda extra' },
    { id: 34, name: 'Investimentos retorno' },
    { id: 35, name: 'Poupança' }
];

export enum Categories {
    'Educação' = 1,
    'Alimentação',
    'Lazer',
    'Hobbies',
    'Assinaturas',
    'Casa',
    'Compras',
    'Saúde',
    'Cuidados pessoais',
    'Dívidas',
    'Família',
    'Impostos',
    'Transporte',
    'Viagens',
    'Doações',
    'Investimentos',
    'Emergências',
    'Animais de estimação',
    'Roupas',
    'Telefonia e Internet',
    'Presentes',
    'Tecnologia',
    'Entretenimento',
    'Beleza e cosméticos',
    'Carro',
    'Seguros',
    'Saúde mental',
    'Imóveis',
    'Cuidado infantil',
    'Aposentadoria',
    'Salário',
    'Bônus',
    'Renda extra',
    'Investimentos retorno',
    'Poupança'
}
